name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: boazhalter
        password: ${{ secrets.GH_PACKAGES_TOKEN }}
    
    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GH_PACKAGES_TOKEN }}" | docker login ghcr.io -u boazhalter --password-stdin


    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ghcr.io/boazhalter/deel:latest

    - name: Run tests
      run: |
        docker run --rm -d -p 5000:5000 --name flask-ip-reverser ghcr.io/boazhalter/deel:latest
        # Add any specific tests you want to run here
        # Wait for the container to be ready
        for i in {1..30}; do
          if curl -f http://localhost:5000; then
            echo "Application is up and running!"
            exit 0
          else
            echo "Waiting for the application to start..."
            sleep 1
          fi
        done
        echo "Application did not start in time"
        
        # For now, just check if the container is running
        sleep 10
        docker logs flask-ip-reverser
        curl -f http://127.0.0.1:5000 || exit 1
       
        docker stop flask-ip-reverser
